### ISSUE TITLE
Cooler won't pack bundles

### ISSUE THREAD

**Issue by yangm97** [alebcay/cooler#10]
[~]$ cooler export cooler --no-port
Creating working directory...
Reading configured taps...
Reading installed formulae...
Reading installed casks...
Packing bundle...
/usr/local/bin/cooler: line 139: ./cooler: Is a directory
[~]$

**Comment by alebcay** [comment]
Thanks for the bug report; unfortunately, I think this particular project has outgrown me a bit. Writing it in a single Bash script has obfuscated it a lot, and it's difficult to debug at this point. Lessons learned, I suppose.

I should probably place an abandonment/deprecation notice on the front README to make this more clear. Perhaps I may attempt a rewrite of Cooler sometime. For now, I don't think I can resolve this.

**Comment by yangm97** [comment]
Got it.
