### ISSUE TITLE
Does not capture list of casks

### ISSUE THREAD

**Issue by malford** [alebcay/cooler#5]
I was having trouble with the current version as it is not capturing my list of casks. 

So I changed like 114 from 
`if [ ! "$3" = "--no-cask" -a ! "$3" = "--no-brew" -a ! "$4" = "--no-cask" -a "$4" = "--no-brew" -a ! "$5" = "--no-cask" -a "$5" = "--no-brew" ]`
to
`if [ ! "$3" = "--no-cask" -a ! "$4" = "--no-cask" -a ! "$5" = "--no-cask" ]`

But not sure if this conditional covers all scenarios but doing it this way captures my environment effectively.

**Comment by alebcay** [comment]
What happens if you specify `--no-brew` now? Does it still get your casks?

**Comment by malford** [comment]
with the `--no-brew` option it does still capture the casks. I suppose that is not intended behavior.

**Comment by alebcay** [comment]
> with the `--no-brew` option it does still capture the casks. I suppose that is not intended behavior.

Yes, that's correct. `--no-brew` is supposed to imply `--no-cask` (hence my code), but I may change that in a future release pretty soon.

**Comment by malford** [comment]
turns out that changing the conditional to this worked for me when specifying `--no-brew`:
`if [ ! "$3" = "--no-cask" -a ! "$4" = "--no-cask" -a ! "$5" = "--no-cask" -a ! "$3" = "--no-brew" -a ! "$4" = "--no-brew" -a ! "$5" = "--no-brew" ]`

**Comment by alebcay** [comment]
That's very strange. I wouldn't think the order of `and` statements would matter (without further parenthesis). I'll change this line in the next release. Thanks for your find!
