### ISSUE TITLE
add mackup support

### ISSUE THREAD

**Issue by tcarlsen** [alebcay/cooler#8]
love the idea of this tool working together with [mackup](https://github.com/lra/mackup)

**Comment by alebcay** [comment]
Already added:

```
cooler export someBundleName --mackup
```

will export your Mackup settings with the bundle, and you can then import the settings with

```
cooler import someBundleName
```

Please note that support for Mackup is shaky at best at this time, but I would appreciate if you took the time to test this feature.

**Comment by tcarlsen** [comment]
Cool! I'll do that!

**Comment by tcarlsen** [comment]
does the --mackup argument just run mackup and with the foldername `someBundleName`???

I got a whole new folder with all the mackup files now, the right think should be to force mackup to include the `someBundleName` in its already created folder

**Comment by alebcay** [comment]
Right now, it does this:
1. Make a bundle, like normally.
2. Add any other stuff in, e.g. Homebrew, Macports...
3. Use config file to direct `mackup` export to this working directory.
4. Uninstall `mackup` to undo changes to the host system (in case these files are going cross-machine).
5. Remove config file.
6. Zip up/clean up the bundle.
